export const mySkills = [
  { title: "Python", icon: "python" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "SQL", icon: "sql" },
  { title: "C#", icon: "csharp" },
  { title: "React", icon: "react" },
  { title: "Next.js", icon: "nextjs" },
  { title: "React Native", icon: "react" },
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: ".NET", icon: "dotnet" },
  { title: "REST APIs", icon: "api" },
  { title: "PostgreSQL", icon: "postgresql" },
  { title: "SQL Server", icon: "sql" },
  { title: "Database Design", icon: "database" },
  { title: "LLMs", icon: "ai" },
  { title: "Prompt Engineering", icon: "ai" },
  { title: "Sentiment Analysis", icon: "ai" },
  { title: "Machine Learning", icon: "ai" },
  { title: "Data Analysis", icon: "analytics" },
  { title: "Power BI", icon: "analytics" },
  { title: "Tableau", icon: "analytics" },
  { title: "Microsoft Fabric", icon: "analytics" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "Jira", icon: "jira" },
  { title: "Confluence", icon: "confluence" },
  { title: "Figma", icon: "figma" },
];